# Generated by Django 3.1.7 on 2022-05-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_auto_20211029_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='onboarded_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
