# Generated by Django 3.1.7 on 2024-06-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0004_pushnotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotifications',
            name='user',
        ),
    ]
