# Generated by Django 3.1.7 on 2024-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0005_remove_pushnotifications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotifications',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='pushnotifications',
            name='sechudeled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushnotifications',
            name='task_type',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('ONE-TIME-TASK', 'ONE-TIME-TASK')], max_length=20, null=True),
        ),
    ]
