# Generated by Django 3.1.7 on 2024-06-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0006_auto_20240618_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotifications',
            old_name='sechudeled_date',
            new_name='scheduled_date',
        ),
    ]
